Add Jaxb to POM as this is affecting the tests - causing java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException due to deprecated Java EE API modules in Java 11